project:
  type: website
  output-dir: docs

website:
  title: "jingyi.github.io"
  navbar:
    left:
      - href: demo website.qmd
        text: Final Project
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

