project:
  type: website
  output-dir: docs

website:
  title: "jingyi.github.io"
  navbar:
    left:
      - href: Final project-Health conditions among children under age 18.qmd
        text: Final Project-Health conditions
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

